name: flutter_training
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  zxcvbn: ^1.0.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.13.0
  get: ^4.7.2
  http: ^1.4.0
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  firebase_core: ^3.14.0
  firebase_analytics: ^11.5.0
  firebase_crashlytics: ^4.3.7
  firebase_remote_config: ^5.4.5
  firebase_auth: ^5.6.0
  shared_preferences: ^2.5.3
  flutter_slidable: ^4.0.0
  share_plus: ^11.0.0
  flutter_bloc: ^9.1.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  path: ^1.9.1
  qr_flutter: ^4.1.0
  screen_brightness: ^2.1.5
  permission_handler: ^12.0.0+1
  contacts_service: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  retrofit_generator: ^9.2.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  fonts: 
    - family: Oswald
      fonts: 
        - asset: assets/font/Oswald-Regular.ttf
          weight: 400
        - asset: assets/font/Oswald-Medium.ttf
          weight: 500
  assets:
    - assets/icon/
    - assets/image/
    - assets/json/
    - assets/image/workouts/
    
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true