// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWyoU3KraxafA-8h-AhfIrqdoWyanwvIg',
    appId: '1:534720101182:web:ee1a7577fe65afa8b60a6f',
    messagingSenderId: '534720101182',
    projectId: 'flavius-ntc',
    authDomain: 'flavius-ntc.firebaseapp.com',
    storageBucket: 'flavius-ntc.firebasestorage.app',
    measurementId: 'G-5GCYZ0TEEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmN-4XXiNkJnh5lQNNNexwYOG5B3K6rzw',
    appId: '1:534720101182:android:28f288e848bde182b60a6f',
    messagingSenderId: '534720101182',
    projectId: 'flavius-ntc',
    storageBucket: 'flavius-ntc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuoKKICCG5UOBmnzB0Y8uejMGOzcRzg_U',
    appId: '1:534720101182:ios:37fd37d8ac7ad626b60a6f',
    messagingSenderId: '534720101182',
    projectId: 'flavius-ntc',
    storageBucket: 'flavius-ntc.firebasestorage.app',
    iosBundleId: 'com.flavius.flutterTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuoKKICCG5UOBmnzB0Y8uejMGOzcRzg_U',
    appId: '1:534720101182:ios:b4e345119c786f63b60a6f',
    messagingSenderId: '534720101182',
    projectId: 'flavius-ntc',
    storageBucket: 'flavius-ntc.firebasestorage.app',
    iosBundleId: 'com.example.flutterTraining',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWyoU3KraxafA-8h-AhfIrqdoWyanwvIg',
    appId: '1:534720101182:web:3188de199b7f0b60b60a6f',
    messagingSenderId: '534720101182',
    projectId: 'flavius-ntc',
    authDomain: 'flavius-ntc.firebaseapp.com',
    storageBucket: 'flavius-ntc.firebasestorage.app',
    measurementId: 'G-BPBNLD41Z7',
  );

}